name: flutter_hk
description: Flutter plugin to play hikvision camera with 8000 protocol. It used hikvision native library, *.so for java and *.a for ios.
version: 2.0.0
# author: TrevorDu <duchunwang@gmail.com>
homepage: https://github.com/duchunwang/flutter_hk

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: jinhx.cn.flutter_hk
    pluginClass: FlutterHkPlugin
